# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

secondary_prompt:
    template: '❯❯ '
    foreground: blue
    background: transparent
transient_prompt:
    template: '❯ '
    foreground: blue
    background: transparent
    newline: true
blocks:
    - type: prompt
      alignment: left
      segments:
        - properties:
            cache_duration: none
          template: "\U000F0B5F  "
          foreground: darkGray
          background: transparent
          type: session
          style: plain
        - properties:
            cache_duration: none
            style: full
          template: '{{ .Path }}'
          foreground: blue
          background: transparent
          type: path
          style: plain
        - properties:
            branch_icon: ' '
            cache_duration: none
            commit_icon: '@'
            fetch_status: true
          template: ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <green>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
          foreground: green
          background: transparent
          type: git
          style: plain
        - properties:
            cache_duration: none
          template: '{{ if .Segments.Contains "Git" }}❯{{ else }} ❯{{ end }}'
          foreground: blue
          background: transparent
          type: text
          style: plain
      newline: true
version: 3
final_space: true
