if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
    eval "$(oh-my-posh init zsh --config ~/dotfiles/config/oh-my-posh.yml)"
fi

# Plugins
plugins=(git)
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

## User configuration
export CLICOLOR=1
export COLORTERM=1
export HISTFILE=$HOME/.zsh_history
export SAVEHIST=5000

# Bind CTRL + arrows
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

source <(fzf --zsh)

eval "$(zoxide init zsh)"

## Toolchains & languages

. "$HOME/.cargo/env"

## Aliases
alias sshserver="ssh root@$SERVER_IP"
alias v="nvim"
alias zshupd="exec zsh"
alias vedit="nvim ~/.config/nvim"
alias zedit="nvim ~/.zshrc"
alias wedit="nvim ~/.config/wezterm/wezterm.lua"

alias st="swift test 2>&1 | xcbeautify"
alias sb="swift build"
alias sr="swift run"

alias ga="git add"
alias gc="git commit"
alias gu="git fetch && git pull"
alias gp="git push"

alias zephyr="source ~/zephyr-venv/bin/activate"
